baseURL = "https://mendelmaleh.gq"
title = "Mendel Elmaleh"
theme = "simple"
# enableGitInfo = true

[author]
  name = "Mendel Elmaleh"

[params]

  homeSubtitle = "software developer"

  [[params.social]]
    name = "github"
    url = "https://github.com/mendelmaleh"

  [[params.social]]
    name = "telegram"
    url = "https://t.me/rastamanjohn"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About me"
    url = "about/"
    weight = 20
